### ISSUE TITLE
[Feature] Show keybinds for commands

### ISSUE THREAD

**Issue by FrancisMurillo** [ptrv/helm-smex#2]
It would be nice if the command key binding is also displayed like with `helm-M-x` as in it is displayed as `helm-M-x (M-x)` in `helm-smex` buffer.

**Comment by ptrv** [comment]
Hi,

thanks for the suggestion. I've added the feature in 7af4e4b44671f739b39584fc50c20084700701ac
You need to set `helm-smex-show-bindings` to `t` to enable it.

**Comment by FrancisMurillo** [comment]
Many thanks
