### ISSUE TITLE
No any keybindings with  helm-smex-major-mode-commands

### ISSUE THREAD

**Issue by 11111000000** [ptrv/helm-smex#3]
**Expected behavior**

helm-smex-major-mode-commands shows suggestions with keys (if available)

**Actual behavior from emacs-helm.sh if possible**

helm-smex-major-mode-commands shows suggestions without any keybindings

**Steps to reproduce (recipe)**

<S-M-x> (or <M-x> helm-smex-major-mode-commands <RET> )

**Describe versions of helm, emacs, operating system etc.**

helm from melpa

**Comment by ptrv** [comment]
`helm-smex` is not part of `helm` so `emacs-helm.sh` does not include `helm-smex`. What did you actually test?

Did you set `helm-smex-show-bindings` to `t`?

For me it works and `helm-smex-major-mode-commands` shows keybindings.

**Comment by 11111000000** [comment]
it works! thanks you!
