### ISSUE TITLE
Set this-command and real-this-command

### ISSUE THREAD

**Issue by wasamasa** [ptrv/helm-smex#4]
I've noticed that my own version of this package didn't work correctly when invoking `M-x auto-insert`.  It turns out this command checks for `this-command` and `execute-extended-command` sets it (and `real-this-command`) to the command to be executed.  I've worked around this issue with the following code you might want to adapt:

```elisp
(defun helm-smex-execute-command (command)
  (when (commandp command)
    (setq this-command command)
    (setq real-this-command command)
    (let ((prefix-arg current-prefix-arg))
      (command-execute command 'record)
      (smex-rank command))))
```

**Comment by ptrv** [comment]
Thanks for the suggestion. Added with https://github.com/ptrv/helm-smex/commit/4f6d131a0913efa97268476921b4aa263a35d9b7
